// Electron main process for a Lamp game (generated by Lighthouse).
//
// Serves the web bundle in app/ over a custom `app://` scheme whose responses
// carry the cross-origin-isolation headers (COOP/COEP), so the page loads
// crossOriginIsolated and SharedArrayBuffer is available. This replaces the web
// bundle's service worker, which cannot run on a custom scheme; the shell's
// registration snippet sees the isolation and exits, so the shell runs
// byte-identical to the web build.
//
// The renderer is fully locked down (sandbox, context isolation, no Node
// integration, no preload): saves ride the same localStorage-backed broker as
// the web build. See devdocs/lighthouse.md ("Electron") and devdocs/sandbox.md.
//
// LAMP_SMOKE=1 runs a headless self-check instead of showing the window:
// prints `LAMP_SMOKE {"isolated":…,"sab":…,"booted":…}` (cross-origin
// isolation, SharedArrayBuffer, and the game's first output reaching the
// transcript) and exits 0 iff all three hold.

const { app, BrowserWindow, net, protocol } = require("electron");
const path = require("path");
const { pathToFileURL } = require("url");

const APP_DIR = path.join(__dirname, "app");
const SMOKE = !!process.env.LAMP_SMOKE;

protocol.registerSchemesAsPrivileged([
    { scheme: "app", privileges: { standard: true, secure: true, supportFetchAPI: true } },
]);

function serveApp(request) {
    const rel = decodeURIComponent(new URL(request.url).pathname).replace(/^\/+/, "") || "index.html";
    const file = path.normalize(path.join(APP_DIR, rel));
    if (!file.startsWith(APP_DIR + path.sep)) {
        return new Response("forbidden", { status: 403 });
    }
    return net.fetch(pathToFileURL(file).toString()).then((res) => {
        const headers = new Headers(res.headers);
        headers.set("Cross-Origin-Opener-Policy", "same-origin");
        headers.set("Cross-Origin-Embedder-Policy", "require-corp");
        headers.set("Cross-Origin-Resource-Policy", "same-origin");
        return new Response(res.body, { status: res.status, headers });
    });
}

app.whenReady().then(() => {
    protocol.handle("app", serveApp);

    const win = new BrowserWindow({
        width: 1000,
        height: 720,
        show: false,
        webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false },
    });
    if (!SMOKE) win.once("ready-to-show", () => win.show());
    if (SMOKE) {
        win.webContents.once("did-finish-load", async () => {
            const result = await win.webContents.executeJavaScript(`(async () => {
                const text = () => (document.getElementById("transcript")?.textContent || "").trim();
                for (let i = 0; i < 50 && !text(); i++) await new Promise((r) => setTimeout(r, 100));
                return JSON.stringify({
                    isolated: self.crossOriginIsolated,
                    sab: typeof SharedArrayBuffer !== "undefined",
                    booted: text().length > 0,
                });
            })()`);
            console.log(`LAMP_SMOKE ${result}`);
            const check = JSON.parse(result);
            app.exit(check.isolated && check.sab && check.booted ? 0 : 1);
        });
    }
    win.loadURL("app://game/index.html");
});

app.on("window-all-closed", () => app.quit());
