// Electron main process for a Lamp game (generated by Lighthouse).
//
// Serves the web bundle in app/ over a custom `app://` scheme whose responses
// carry the cross-origin-isolation headers (COOP/COEP), so the page loads
// crossOriginIsolated and SharedArrayBuffer is available. This replaces the web
// bundle's service worker, which cannot run on a custom scheme; the shell's
// registration snippet sees the isolation and exits, so the shell runs
// byte-identical to the web build.
//
// The renderer is fully locked down (sandbox, context isolation, no Node
// integration). Saves are real files under the app's userData directory — the
// Electron-only capability the web build backs with localStorage: preload.js
// exposes the save broker's four operations as `lampSaves`, serviced here over
// IPC. The broker protocol is unchanged; only the shell's backing differs. See
// devdocs/lighthouse.md ("Electron") and devdocs/sandbox.md.
//
// LAMP_SMOKE=1 runs a headless self-check instead of showing the window:
// prints `LAMP_SMOKE {"isolated":…,"sab":…,"booted":…,"saves":…}` (cross-origin
// isolation, SharedArrayBuffer, the game's first output reaching the
// transcript, and a save round-trip through the fs bridge) and exits 0 iff all
// four hold.

const { app, BrowserWindow, ipcMain, net, protocol } = require("electron");
const fs = require("fs");
const path = require("path");
const { pathToFileURL } = require("url");

const APP_DIR = path.join(__dirname, "app");
const SMOKE = !!process.env.LAMP_SMOKE;

protocol.registerSchemesAsPrivileged([
    { scheme: "app", privileges: { standard: true, secure: true, supportFetchAPI: true } },
]);

function serveApp(request) {
    const rel = decodeURIComponent(new URL(request.url).pathname).replace(/^\/+/, "") || "index.html";
    const file = path.normalize(path.join(APP_DIR, rel));
    if (!file.startsWith(APP_DIR + path.sep)) {
        return new Response("forbidden", { status: 403 });
    }
    return net.fetch(pathToFileURL(file).toString()).then((res) => {
        const headers = new Headers(res.headers);
        headers.set("Cross-Origin-Opener-Policy", "same-origin");
        headers.set("Cross-Origin-Embedder-Policy", "require-corp");
        headers.set("Cross-Origin-Resource-Policy", "same-origin");
        return new Response(res.body, { status: res.status, headers });
    });
}

// One save per file under userData/saves, stored as JSON { key, data, meta }.
// The filename is base64url(key), so any player-typed slot name is
// filesystem-safe on every platform; list() reads the key back from the file
// content, never from the name.
function savesDir() {
    return path.join(app.getPath("userData"), "saves");
}

function saveFile(key) {
    return path.join(savesDir(), Buffer.from(String(key), "utf8").toString("base64url") + ".json");
}

function registerSaveHandlers() {
    ipcMain.handle("lamp-save-write", (event, key, data, meta) => {
        if (typeof key !== "string" || typeof data !== "string") throw new Error("bad save request");
        fs.mkdirSync(savesDir(), { recursive: true });
        fs.writeFileSync(saveFile(key), JSON.stringify({ key, data, meta: meta || null }), "utf8");
    });
    ipcMain.handle("lamp-save-read", (event, key) => {
        try {
            return JSON.parse(fs.readFileSync(saveFile(key), "utf8")).data;
        } catch {
            return null;
        }
    });
    ipcMain.handle("lamp-save-list", (event, prefix) => {
        let names;
        try {
            names = fs.readdirSync(savesDir());
        } catch {
            return [];
        }
        const rows = [];
        for (const name of names) {
            if (!name.endsWith(".json")) continue;
            try {
                const row = JSON.parse(fs.readFileSync(path.join(savesDir(), name), "utf8"));
                if (row && typeof row.key === "string" && row.key.startsWith(String(prefix)) && row.meta) {
                    rows.push({ key: row.key, meta: row.meta });
                }
            } catch {
                // Skip a corrupt save file rather than fail the whole list.
            }
        }
        return rows;
    });
    ipcMain.handle("lamp-save-remove", (event, key) => {
        fs.rmSync(saveFile(key), { force: true });
    });
}

app.whenReady().then(() => {
    protocol.handle("app", serveApp);
    registerSaveHandlers();

    const win = new BrowserWindow({
        width: 1000,
        height: 720,
        show: false,
        webPreferences: {
            sandbox: true,
            contextIsolation: true,
            nodeIntegration: false,
            preload: path.join(__dirname, "preload.js"),
        },
    });
    if (!SMOKE) win.once("ready-to-show", () => win.show());
    if (SMOKE) {
        win.webContents.once("did-finish-load", async () => {
            const result = await win.webContents.executeJavaScript(`(async () => {
                const text = () => (document.getElementById("transcript")?.textContent || "").trim();
                for (let i = 0; i < 50 && !text(); i++) await new Promise((r) => setTimeout(r, 100));
                let saves = false;
                try {
                    const key = "lamp-smoke#probe";
                    await window.lampSaves.write(key, "blob", { name: "probe", savedAt: "smoke" });
                    const rows = await window.lampSaves.list("lamp-smoke#");
                    const data = await window.lampSaves.read(key);
                    await window.lampSaves.remove(key);
                    const gone = await window.lampSaves.read(key);
                    saves = data === "blob" && rows.length === 1 && rows[0].meta.name === "probe" && gone === null;
                } catch (e) {}
                return JSON.stringify({
                    isolated: self.crossOriginIsolated,
                    sab: typeof SharedArrayBuffer !== "undefined",
                    booted: text().length > 0,
                    saves,
                });
            })()`);
            console.log(`LAMP_SMOKE ${result}`);
            const check = JSON.parse(result);
            app.exit(check.isolated && check.sab && check.booted && check.saves ? 0 : 1);
        });
    }
    win.loadURL("app://game/index.html");
});

app.on("window-all-closed", () => app.quit());
