// Preload bridge for fs-backed saves (generated by Lighthouse).
//
// Runs sandboxed with context isolation. The page — and therefore the game
// shell — sees exactly one extra global, `lampSaves`: the save broker's four
// storage operations plus the two prompts, forwarded to the main process. The
// prompts open native OS save/open dialogs (so shell.js skips its HTML
// modals); saves are real .lampsave files wherever the player puts them.
// Nothing else crosses the boundary. shell.js prefers this bridge over its
// localStorage default when present. See devdocs/lighthouse.md ("Electron")
// and devdocs/sandbox.md.

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("lampSaves", {
    list: (prefix) => ipcRenderer.invoke("lamp-save-list", prefix),
    read: (key) => ipcRenderer.invoke("lamp-save-read", key),
    write: (key, data, meta) => ipcRenderer.invoke("lamp-save-write", key, data, meta),
    remove: (key) => ipcRenderer.invoke("lamp-save-remove", key),
    promptSave: (prefix) => ipcRenderer.invoke("lamp-save-prompt", prefix),
    promptRestore: (prefix) => ipcRenderer.invoke("lamp-restore-prompt", prefix),
});
