// Preload bridge for fs-backed saves (generated by Lighthouse).
//
// Runs sandboxed with context isolation. The page — and therefore the game
// shell — sees exactly one extra global, `lampSaves`: the save broker's four
// operations, forwarded to the main process, which stores saves as files under
// the app's userData directory. Nothing else crosses the boundary. shell.js
// prefers this bridge over its localStorage default when present. See
// devdocs/lighthouse.md ("Electron") and devdocs/sandbox.md.

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("lampSaves", {
    list: (prefix) => ipcRenderer.invoke("lamp-save-list", prefix),
    read: (key) => ipcRenderer.invoke("lamp-save-read", key),
    write: (key, data, meta) => ipcRenderer.invoke("lamp-save-write", key, data, meta),
    remove: (key) => ipcRenderer.invoke("lamp-save-remove", key),
});
