#!/usr/bin/env node
/* Generated by Lantern */
const lamplighter = require("../src/lamplighter");
lamplighter.bootstrapBuiltins();

function readline() {
    const fs = require("fs");
    const buf = Buffer.alloc(1);
    let result = "";
    while (true) {
        const n = fs.readSync(0, buf, 0, 1);
        if (n === 0) break;
        const ch = buf.toString("utf8", 0, 1);
        if (ch === "\n") break;
        result += ch;
    }
    return result;
}

function split(input) {
    const words = input.trim().split(/\s+/).filter((w) => w.length > 0);
    return lamplighter.makeList(words);
}

lamplighter.defineKind("color", lamplighter.enum("red", "green", "blue"));
lamplighter.defineKind("reltype", lamplighter.enum("dev", "beta", "final"));

const color = lamplighter.kind("color");
const reltype = lamplighter.kind("reltype");

lamplighter.defineType("game", [], {"author":"string","version":"int","release":"reltype"});
lamplighter.defineType("room", [], {});
lamplighter.defineType("direction", [], {"inverse":"direction"});

const game = lamplighter.type("game");
const room = lamplighter.type("room");
const direction = lamplighter.type("direction");

lamplighter.defineRelation("connects", {"source":"room","dir":"direction","target":"room"}, "connects [source] [dir] [target]", ["dir"]);

const connects = lamplighter.type("connects");

lamplighter.createObject("game", "Relation 22", { "author": "Test Author", "version": 1, "release": "dev" });
const foyer = lamplighter.createObject("room", "foyer", {  });
const hall = lamplighter.createObject("room", "hall", {  });
const study = lamplighter.createObject("room", "study", {  });
const north = lamplighter.createObject("direction", "north", {  });
const south = lamplighter.createObject("direction", "south", {  });
const east = lamplighter.createObject("direction", "east", {  });
const west = lamplighter.createObject("direction", "west", {  });
north.inverse = lamplighter.getObject("south");
south.inverse = lamplighter.getObject("north");
east.inverse = lamplighter.getObject("west");
west.inverse = lamplighter.getObject("east");

lamplighter.defineGlobal("USE OXFORD COMMA", false);
lamplighter.defineGlobal("PI", 3.141592653);

function check() {
    if ((lamplighter.queryRelation("connects", { "source": lamplighter.getObject("foyer"), "dir": lamplighter.getObject("north"), "target": lamplighter.getObject("hall") }).length > 0)) {
        lamplighter.print("foyer connects north to hall");
    } else {
        lamplighter.print("none");
    }
}

lamplighter.onEvent("startup", () => {
    check();
    lamplighter.addRelation("connects", { "source": lamplighter.getObject("foyer"), "dir": lamplighter.getObject("north"), "target": lamplighter.getObject("hall") });
    check();
    lamplighter.removeRelation("connects", { "source": lamplighter.getObject("foyer"), "dir": lamplighter.getObject("north"), "target": lamplighter.ANY });
    lamplighter.addRelation("connects", { "source": lamplighter.getObject("foyer"), "dir": lamplighter.getObject("east"), "target": lamplighter.getObject("study") });
    check();
    lamplighter.removeRelation("connects", { "source": lamplighter.ANY, "dir": lamplighter.ANY, "target": lamplighter.ANY });
    check();
});

lamplighter.run();
