// Expressions whose emitted form is already self-delimiting (literals, variable
// names, property-access chains, function calls) and never need extra parens.
const SAFE_ATOM = new Set([
    "StringLiteral", "NumberLiteral", "BooleanLiteral", "NoneLiteral",
    "VariableExpr", "PropertyAccess", "GlobalExpr", "ParenNameExpr", "Concat",
]);

// JS operator precedence for the binary/unary expression kinds we emit.
const EXPR_JS_PREC = {
    PowerExpr: 15,
    MultiplyExpr: 14,
    DivideExpr: 14,
    SubtractExpr: 13,
    LessThanExpr: 12,
    EqualsExpr: 11,
};

// Emits `expr` wrapped in parens when JS precedence requires it.
//   rightOperand: true when this is the right side of a left-associative op
//     (same precedence also needs parens: `a-(b-c)` ≠ `a-b-c`).
//   leftOfPower: true when this is the left side of `**`; JS disallows any
//     unparenthesized non-atom there, so wrap everything that isn't an atom.
function wrapIfNeeded(expr, parentPrec, globalNames, { rightOperand = false, leftOfPower = false } = {}) {
    if (leftOfPower && !SAFE_ATOM.has(expr.kind)) {
        return `(${emitExpression(expr, globalNames)})`;
    }
    const childPrec = EXPR_JS_PREC[expr.kind];
    if (childPrec === undefined) return emitExpression(expr, globalNames);
    const needsParens = rightOperand ? childPrec <= parentPrec : childPrec < parentPrec;
    return needsParens ? `(${emitExpression(expr, globalNames)})` : emitExpression(expr, globalNames);
}

function emitProgram(programAst, options = {}) {
    const runtimeRequirePath = options.runtimeRequirePath || "../lamplighter";
    const globalDeclNodes = programAst.nodes.filter((node) => node.kind === "GlobalDecl");
    const globalAssignNodes = programAst.nodes.filter((node) => node.kind === "GlobalAssign");
    const kindNodes = programAst.nodes.filter((node) => node.kind === "KindDecl");
    const typeNodes = programAst.nodes.filter((node) => node.kind === "TypeDecl");
    const objectNodes = programAst.nodes.filter((node) => node.kind === "ObjectDecl");
    const eventNodes = programAst.nodes.filter((node) => node.kind === "EventHandler");

    const kindNames = new Set(kindNodes.map((n) => n.name));

    const lines = [];
    lines.push("#!/usr/bin/env node");
    lines.push("/* Generated by Lantern */");
    lines.push(`const lamplighter = require(${JSON.stringify(runtimeRequirePath)});`);
    lines.push("lamplighter.bootstrapBuiltins();");
    lines.push("");

    for (const kindNode of kindNodes) {
        lines.push(emitKindDecl(kindNode));
    }

    if (kindNodes.length > 0) {
        lines.push("");
    }

    for (const kindNode of kindNodes) {
        lines.push(`const ${kindNode.name} = lamplighter.kind(${JSON.stringify(kindNode.name)});`);
    }

    if (kindNodes.length > 0) {
        lines.push("");
    }

    // Merge reopened type declarations: multiple TypeDecl nodes with the same name → one defineType call
    const mergedTypes = new Map();
    for (const typeNode of typeNodes) {
        if (!mergedTypes.has(typeNode.name)) {
            mergedTypes.set(typeNode.name, { ...typeNode, fields: [...typeNode.fields] });
        } else {
            mergedTypes.get(typeNode.name).fields.push(...typeNode.fields);
        }
    }

    for (const typeNode of mergedTypes.values()) {
        lines.push(emitTypeDecl(typeNode));
    }

    if (mergedTypes.size > 0) {
        lines.push("");
    }

    for (const typeNode of mergedTypes.values()) {
        lines.push(`const ${typeNode.name} = lamplighter.type(${JSON.stringify(typeNode.name)});`);
    }

    if (mergedTypes.size > 0) {
        lines.push("");
    }

    for (const objectNode of objectNodes) {
        lines.push(emitObjectDecl(objectNode, mergedTypes, kindNames));
    }

    // Set object-typed fields after all objects exist so forward references work
    const objectFieldInits = objectNodes.flatMap((n) => emitObjectFieldInits(n, mergedTypes, kindNames));
    for (const init of objectFieldInits) {
        lines.push(init);
    }

    if (objectNodes.length > 0) {
        lines.push("");
    }

    for (const globalDeclNode of globalDeclNodes) {
        lines.push(emitGlobalDecl(globalDeclNode, kindNames));
    }

    if (globalDeclNodes.length > 0) {
        lines.push("");
    }

    for (const globalAssignNode of globalAssignNodes) {
        lines.push(emitGlobalAssign(globalAssignNode));
    }

    if (globalAssignNodes.length > 0) {
        lines.push("");
    }

    const changeHandlerNodes = programAst.nodes.filter((node) => node.kind === "ChangeHandler");
    const globalNames = new Set(globalDeclNodes.map((n) => n.name));

    for (const eventNode of eventNodes) {
        lines.push(emitEventHandler(eventNode, globalNames));
    }

    for (const changeNode of changeHandlerNodes) {
        lines.push(emitChangeHandler(changeNode, globalNames));
    }

    lines.push("");
    lines.push("lamplighter.run();");
    lines.push("");

    return `${lines.join("\n")}`;
}

const PRIMITIVE_TYPES = new Set(["bool", "int", "real", "string"]);

function resolveFieldType(typeName, fieldName, mergedTypes) {
    const visited = new Set();
    function search(name) {
        if (visited.has(name)) return null;
        visited.add(name);
        const typeNode = mergedTypes.get(name);
        if (!typeNode) return null;
        for (const f of typeNode.fields) {
            if (f.fieldName === fieldName) return f.typeName;
        }
        for (const parent of (typeNode.parents || [])) {
            const result = search(parent);
            if (result !== null) return result;
        }
        return null;
    }
    return search(typeName);
}

function isObjectTypedField(field, typeName, mergedTypes, kindNames) {
    if (field.value.kind !== "StringLiteral") return false;
    const fieldType = resolveFieldType(typeName, field.fieldName, mergedTypes);
    return fieldType !== null && !PRIMITIVE_TYPES.has(fieldType) && !kindNames.has(fieldType);
}

function objectRef(objectName) {
    return /^[A-Za-z_][A-Za-z0-9_]*$/.test(objectName)
        ? objectName
        : `lamplighter.getObject(${JSON.stringify(objectName)})`;
}

function emitGlobalDecl(node, kindNames = new Set()) {
    let valueExpr;
    if (node.value.kind === "NoneLiteral") {
        valueExpr = "null";
    } else if (
        node.value.kind === "StringLiteral"
        && !PRIMITIVE_TYPES.has(node.typeName)
        && !kindNames.has(node.typeName)
    ) {
        // Bare identifier value for an object-typed global — treat as object name reference
        valueExpr = `lamplighter.getObject(${JSON.stringify(node.value.value)})`;
    } else {
        valueExpr = emitValue(node.value);
    }
    return `lamplighter.defineGlobal(${JSON.stringify(node.name)}, ${valueExpr});`;
}

function emitGlobalAssign(node) {
    return `lamplighter.setGlobal(${JSON.stringify(node.name)}, ${emitValue(node.value)});`;
}

function emitKindDecl(node) {
    return `lamplighter.defineKind(${JSON.stringify(node.name)}, ${emitKindExpr(node.kindExpr)});`;
}

function emitKindExpr(expr) {
    if (expr.kind === "EnumExpr") {
        const labelArgs = expr.labels.map((l) => JSON.stringify(l)).join(", ");
        return `lamplighter.enum(${labelArgs})`;
    }
    throw new Error(`Unsupported kind expression kind: ${expr.kind}`);
}

function emitTypeDecl(node) {
    const fields = {};
    for (const field of node.fields) {
        fields[field.fieldName] = field.typeName;
    }

    return `lamplighter.defineType(${JSON.stringify(node.name)}, ${JSON.stringify(node.parents || [])}, ${JSON.stringify(fields)});`;
}

function emitObjectDecl(node, mergedTypes = new Map(), kindNames = new Set()) {
    const fields = {};
    for (const field of node.fields) {
        if (!isObjectTypedField(field, node.typeName, mergedTypes, kindNames)) {
            fields[field.fieldName] = emitValue(field.value);
        }
    }

    const pairs = Object.entries(fields).map(([key, value]) => `${JSON.stringify(key)}: ${value}`);
    const call = `lamplighter.createObject(${JSON.stringify(node.typeName)}, ${JSON.stringify(node.objectName)}, { ${pairs.join(", ")} })`;

    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(node.objectName)) {
        return `const ${node.objectName} = ${call};`;
    }
    return `${call};`;
}

function emitObjectFieldInits(node, mergedTypes, kindNames) {
    return node.fields
        .filter((field) => isObjectTypedField(field, node.typeName, mergedTypes, kindNames))
        .map((field) => `${objectRef(node.objectName)}.${field.fieldName} = lamplighter.getObject(${JSON.stringify(field.value.value)});`);
}

function emitValue(valueNode) {
    if (valueNode.kind === "StringLiteral") {
        return JSON.stringify(valueNode.value);
    }
    if (valueNode.kind === "BooleanLiteral") {
        return valueNode.value ? "true" : "false";
    }
    if (valueNode.kind === "NumberLiteral") {
        return String(valueNode.value);
    }
    if (valueNode.kind === "NoneLiteral") {
        return "null";
    }
    throw new Error(`Unsupported value kind: ${valueNode.kind}`);
}

function emitEventHandler(node, globalNames = new Set()) {
    const bodyLines = emitStatementList(node.body, 1, globalNames);
    return [
        `lamplighter.onEvent(${JSON.stringify(node.eventName)}, () => {`,
        ...bodyLines,
        "});",
    ].join("\n");
}

function emitChangeHandler(node, globalNames = new Set()) {
    const bodyLines = emitStatementList(node.body, 1, globalNames);
    return [
        `lamplighter.registerChangeHandler(${JSON.stringify(node.typeName)}, ${JSON.stringify(node.fieldName)}, (self) => {`,
        ...bodyLines,
        "});",
    ].join("\n");
}

function emitStatementList(statements, indentLevel, globalNames = new Set()) {
    return statements.flatMap((statement) => emitStatementLines(statement, indentLevel, globalNames));
}

function emitStatementLines(statement, indentLevel, globalNames = new Set()) {
    const indent = "    ".repeat(indentLevel);

    if (statement.kind === "LetStatement") {
        return [`${indent}let ${statement.name} = ${emitExpression(statement.expr, globalNames)};`];
    }
    if (statement.kind === "PrintStatement") {
        return [`${indent}lamplighter.print(${emitExpression(statement.expr, globalNames)});`];
    }
    if (statement.kind === "AssignStatement") {
        const [head, ...tail] = statement.targetChain;
        const headExpr = globalNames.has(head) ? `lamplighter.getGlobal(${JSON.stringify(head)})` : head;
        if (tail.length === 0) {
            return [`${indent}${headExpr} = ${emitExpression(statement.expr, globalNames)};`];
        }
        const objExpr = tail.length === 1 ? headExpr : `${headExpr}.${tail.slice(0, -1).join(".")}`;
        const fieldName = tail[tail.length - 1];
        return [`${indent}lamplighter.setField(${objExpr}, ${JSON.stringify(fieldName)}, ${emitExpression(statement.expr, globalNames)});`];
    }
    if (statement.kind === "ErrorStatement") {
        return [`${indent}lamplighter.error(${emitExpression(statement.expr, globalNames)});`];
    }
    if (statement.kind === "DispatchStatement") {
        return [`${indent}lamplighter.dispatch(${JSON.stringify(statement.eventName)});`];
    }
    if (statement.kind === "IfStatement") {
        const lines = [`${indent}if (${emitExpression(statement.condition, globalNames)}) {`];
        lines.push(...emitStatementList(statement.thenBody, indentLevel + 1, globalNames));
        lines.push(`${indent}}`);

        if (statement.elseBody) {
            lines[lines.length - 1] = `${indent}} else {`;
            lines.push(...emitStatementList(statement.elseBody, indentLevel + 1, globalNames));
            lines.push(`${indent}}`);
        }

        return lines;
    }
    if (statement.kind === "BreakStatement") {
        return [`${indent}break;`];
    }
    if (statement.kind === "ForStatement") {
        const start = emitExpression(statement.start, globalNames);
        const finish = emitExpression(statement.finish, globalNames);
        const step = emitExpression(statement.step, globalNames);
        const v = statement.varName;
        const lines = [`${indent}for (let ${v} = ${start}; ${v} <= ${finish}; ${v} += ${step}) {`];
        lines.push(...emitStatementList(statement.body, indentLevel + 1, globalNames));
        lines.push(`${indent}}`);
        return lines;
    }
    if (statement.kind === "WhileStatement") {
        const lines = [`${indent}while (${emitExpression(statement.condition, globalNames)}) {`];
        lines.push(...emitStatementList(statement.body, indentLevel + 1, globalNames));
        lines.push(`${indent}}`);
        return lines;
    }
    throw new Error(`Unsupported statement kind: ${statement.kind}`);
}

function emitExpression(expr, globalNames = new Set()) {
    if (expr.kind === "StringLiteral") {
        return JSON.stringify(expr.value);
    }
    if (expr.kind === "VariableExpr") {
        return expr.name;
    }
    if (expr.kind === "BooleanLiteral") {
        return expr.value ? "true" : "false";
    }
    if (expr.kind === "NumberLiteral") {
        return String(expr.value);
    }
    if (expr.kind === "PropertyAccess") {
        const [head, ...tail] = expr.chain;
        const headExpr = globalNames.has(head) ? `lamplighter.getGlobal(${JSON.stringify(head)})` : head;
        return tail.length === 0 ? headExpr : `${headExpr}.${tail.join(".")}`;
    }
    if (expr.kind === "Concat") {
        return `lamplighter.concat(${emitExpression(expr.left, globalNames)}, ${emitExpression(expr.right, globalNames)})`;
    }
    if (expr.kind === "EqualsExpr") {
        return `${emitExpression(expr.left, globalNames)} === ${emitExpression(expr.right, globalNames)}`;
    }
    if (expr.kind === "LessThanExpr") {
        return `${emitExpression(expr.left, globalNames)} < ${emitExpression(expr.right, globalNames)}`;
    }
    if (expr.kind === "MultiplyExpr") {
        return `${wrapIfNeeded(expr.left, 14, globalNames)} * ${wrapIfNeeded(expr.right, 14, globalNames, { rightOperand: true })}`;
    }
    if (expr.kind === "NegateExpr") {
        return `-(${emitExpression(expr.expr, globalNames)})`;
    }
    if (expr.kind === "SubtractExpr") {
        return `${wrapIfNeeded(expr.left, 13, globalNames)} - ${wrapIfNeeded(expr.right, 13, globalNames, { rightOperand: true })}`;
    }
    if (expr.kind === "DivideExpr") {
        return `${wrapIfNeeded(expr.left, 14, globalNames)} / ${wrapIfNeeded(expr.right, 14, globalNames, { rightOperand: true })}`;
    }
    if (expr.kind === "PowerExpr") {
        return `${wrapIfNeeded(expr.left, 15, globalNames, { leftOfPower: true })} ** ${wrapIfNeeded(expr.right, 15, globalNames)}`;
    }
    if (expr.kind === "NoneLiteral") {
        return "null";
    }
    if (expr.kind === "GlobalExpr") {
        return `lamplighter.getGlobal(${JSON.stringify(expr.name)})`;
    }
    if (expr.kind === "ParenNameExpr") {
        const base = `lamplighter.getObject(${JSON.stringify(expr.objectName)})`;
        return expr.fieldChain.length === 0 ? base : `${base}.${expr.fieldChain.join(".")}`;
    }
    throw new Error(`Unsupported expression kind: ${expr.kind}`);
}

module.exports = {
    emitProgram,
};
