// Expressions whose emitted form is already self-delimiting (literals, variable
// names, property-access chains, function calls) and never need extra parens.
const SAFE_ATOM = new Set([
    "StringLiteral", "NumberLiteral", "BooleanLiteral", "NoneLiteral",
    "VariableExpr", "PropertyAccess", "GlobalExpr", "ParenNameExpr", "Concat", "DivideExpr", "CallExpr", "FunctionRefExpr", "FollowExpr", "IndexExpr",
]);

// JS operator precedence for the binary/unary expression kinds we emit.
const EXPR_JS_PREC = {
    PowerExpr: 15,
    MultiplyExpr: 14,
    SubtractExpr: 13,
    LessThanExpr: 12,
    LessOrEqualExpr: 12,
    EqualsExpr: 11,
};

// Emits `expr` wrapped in parens when JS precedence requires it.
//   rightOperand: true when this is the right side of a left-associative op
//     (same precedence also needs parens: `a-(b-c)` ≠ `a-b-c`).
//   leftOfPower: true when this is the left side of `**`; JS disallows any
//     unparenthesized non-atom there, so wrap everything that isn't an atom.
function wrapIfNeeded(expr, parentPrec, globalNames, { rightOperand = false, leftOfPower = false } = {}) {
    if (leftOfPower) {
        // JS forbids an unparenthesized non-atom left of **: -2**n is a SyntaxError.
        const unsafeLeft = !SAFE_ATOM.has(expr.kind)
            || (expr.kind === "NumberLiteral" && expr.value < 0);
        if (unsafeLeft) return `(${emitExpression(expr, globalNames)})`;
    }
    const childPrec = EXPR_JS_PREC[expr.kind];
    if (childPrec === undefined) return emitExpression(expr, globalNames);
    const needsParens = rightOperand ? childPrec <= parentPrec : childPrec < parentPrec;
    return needsParens ? `(${emitExpression(expr, globalNames)})` : emitExpression(expr, globalNames);
}

// Set once at the start of emitProgram and read from statement/expression
// emitters, so they aren't threaded through every emitting function: relation
// field schemas (name -> { fieldName: typeName }), the set of kind names, and
// function parameter types (name -> [typeName]).
let relationFieldSchemas = new Map();
let emitKindNames = new Set();
let functionParamTypes = new Map();
let actionSlotTypes = new Map();

function emitProgram(programAst, options = {}) {
    const nativeJsContents = options.nativeJsContents || [];
    const globalDeclNodes = programAst.nodes.filter((node) => node.kind === "GlobalDecl");
    const globalAssignNodes = programAst.nodes.filter((node) => node.kind === "GlobalAssign");
    const kindNodes = programAst.nodes.filter((node) => node.kind === "KindDecl");
    const typeNodes = programAst.nodes.filter((node) => node.kind === "TypeDecl");
    const relationNodes = programAst.nodes.filter((node) => node.kind === "RelationDecl");
    const objectNodes = programAst.nodes.filter((node) => node.kind === "ObjectDecl");
    const eventNodes = programAst.nodes.filter((node) => node.kind === "EventHandler");
    const functionNodes = programAst.nodes.filter((node) => node.kind === "FunctionDecl");

    const kindNames = new Set(kindNodes.map((n) => n.name));

    emitKindNames = kindNames;
    functionParamTypes = new Map();
    for (const node of programAst.nodes) {
        if (node.kind === "FunctionDecl" || node.kind === "NativeFunctionDecl" || node.kind === "RulebookDecl") {
            functionParamTypes.set(node.name, node.params.map((p) => p.typeName));
        }
    }
    relationFieldSchemas = new Map();
    for (const relationNode of relationNodes) {
        const schema = {};
        for (const field of relationNode.fields) {
            schema[field.fieldName] = field.typeName;
        }
        relationFieldSchemas.set(relationNode.name, schema);
    }
    const actionNodes = programAst.nodes.filter((node) => node.kind === "ActionDecl");
    actionSlotTypes = new Map();
    for (const actionNode of actionNodes) {
        actionSlotTypes.set(actionNode.name, new Map(actionNode.slots.map((s) => [s.fieldName, s.typeName])));
    }

    // Body-only module: no shebang and no runtime require. The sandbox launcher
    // injects `lamplighter` as a context global and is the only supported run
    // path (see devdocs/sandbox.md).
    const lines = [];
    lines.push("/* Generated by Lantern */");
    lines.push("lamplighter.bootstrapBuiltins();");

    for (const jsContent of nativeJsContents) {
        const trimmed = jsContent.trimEnd();
        if (trimmed) {
            lines.push("");
            lines.push(trimmed);
        }
    }

    lines.push("");

    for (const kindNode of kindNodes) {
        lines.push(emitKindDecl(kindNode));
    }

    if (kindNodes.length > 0) {
        lines.push("");
    }

    for (const kindNode of kindNodes) {
        lines.push(`const ${kindNode.name} = lamplighter.kind(${JSON.stringify(kindNode.name)});`);
    }

    if (kindNodes.length > 0) {
        lines.push("");
    }

    // Merge reopened type declarations: multiple TypeDecl nodes with the same name → one defineType call
    const mergedTypes = new Map();
    for (const typeNode of typeNodes) {
        if (!mergedTypes.has(typeNode.name)) {
            mergedTypes.set(typeNode.name, { ...typeNode, fields: [...typeNode.fields] });
        } else {
            mergedTypes.get(typeNode.name).fields.push(...typeNode.fields);
        }
    }

    // An action declaration emits as a type whose parent is the built-in `action`
    // type and whose fields are its slots.
    for (const actionNode of actionNodes) {
        mergedTypes.set(actionNode.name, {
            kind: "TypeDecl",
            name: actionNode.name,
            parents: ["action"],
            fields: [...actionNode.slots],
        });
    }

    for (const typeNode of mergedTypes.values()) {
        lines.push(emitTypeDecl(typeNode));
    }

    if (mergedTypes.size > 0) {
        lines.push("");
    }

    for (const typeNode of mergedTypes.values()) {
        lines.push(`const ${typeNode.name} = lamplighter.type(${JSON.stringify(typeNode.name)});`);
    }

    if (mergedTypes.size > 0) {
        lines.push("");
    }

    for (const relationNode of relationNodes) {
        lines.push(emitRelationDecl(relationNode));
    }

    if (relationNodes.length > 0) {
        lines.push("");
    }

    for (const relationNode of relationNodes) {
        lines.push(`const ${relationNode.name} = lamplighter.type(${JSON.stringify(relationNode.name)});`);
    }

    if (relationNodes.length > 0) {
        lines.push("");
    }

    for (const objectNode of objectNodes) {
        lines.push(emitObjectDecl(objectNode, mergedTypes, kindNames));
    }

    // Set object-typed fields after all objects exist so forward references work
    const objectFieldInits = objectNodes.flatMap((n) => emitObjectFieldInits(n, mergedTypes, kindNames));
    for (const init of objectFieldInits) {
        lines.push(init);
    }

    if (objectNodes.length > 0) {
        lines.push("");
    }

    const relationAssertNodes = programAst.nodes.filter((node) => node.kind === "RelationAssert");
    for (const assertNode of relationAssertNodes) {
        lines.push(emitRelationAssert(assertNode));
    }

    if (relationAssertNodes.length > 0) {
        lines.push("");
    }

    const topLevelRemoveNodes = programAst.nodes.filter(
        (node) => node.kind === "RelationRemove" || node.kind === "DisconnectStatement"
    );
    for (const removeNode of topLevelRemoveNodes) {
        lines.push(
            removeNode.kind === "RelationRemove"
                ? emitRelationRemove(removeNode)
                : emitDisconnect(removeNode)
        );
    }
    if (topLevelRemoveNodes.length > 0) {
        lines.push("");
    }

    for (const globalDeclNode of globalDeclNodes) {
        lines.push(emitGlobalDecl(globalDeclNode, kindNames));
    }

    if (globalDeclNodes.length > 0) {
        lines.push("");
    }

    for (const globalAssignNode of globalAssignNodes) {
        lines.push(emitGlobalAssign(globalAssignNode));
    }

    if (globalAssignNodes.length > 0) {
        lines.push("");
    }

    const changeHandlerNodes = programAst.nodes.filter((node) => node.kind === "ChangeHandler");
    const relationAddHandlerNodes = programAst.nodes.filter((node) => node.kind === "RelationAddHandler");
    const relationRemoveHandlerNodes = programAst.nodes.filter((node) => node.kind === "RelationRemoveHandler");
    const globalNames = new Set(globalDeclNodes.map((n) => n.name));

    const functionGroups = new Map();
    for (let i = 0; i < functionNodes.length; i++) {
        const node = functionNodes[i];
        if (!functionGroups.has(node.name)) functionGroups.set(node.name, []);
        functionGroups.get(node.name).push({ node, definitionIndex: i });
    }

    for (const [name, overloads] of functionGroups) {
        lines.push(emitFunctionGroup(name, overloads, globalNames));
        lines.push("");
    }

    for (const node of programAst.nodes) {
        if (node.kind !== "RulebookDecl") continue;
        lines.push(emitRulebookDecl(node, globalNames));
        lines.push("");
    }

    for (const eventNode of eventNodes) {
        lines.push(emitEventHandler(eventNode, globalNames));
    }

    for (const changeNode of changeHandlerNodes) {
        lines.push(emitChangeHandler(changeNode, globalNames));
    }

    for (const node of programAst.nodes) {
        if (node.kind !== "PhaseRule") continue;
        lines.push(emitPhaseRule(node, globalNames));
    }

    for (const actionNode of actionNodes) {
        for (const template of (actionNode.templates || [])) {
            lines.push(`lamplighter.registerGrammar(${JSON.stringify(actionNode.name)}, ${JSON.stringify(template)});`);
        }
    }

    for (const node of relationAddHandlerNodes) {
        lines.push(emitRelationAddHandler(node, globalNames));
    }

    for (const node of relationRemoveHandlerNodes) {
        lines.push(emitRelationRemoveHandler(node, globalNames));
    }

    lines.push("");
    lines.push("lamplighter.run();");
    lines.push("");

    return `${lines.join("\n")}`;
}

const PRIMITIVE_TYPES = new Set(["bool", "int", "real", "string"]);

function resolveFieldType(typeName, fieldName, mergedTypes) {
    const visited = new Set();
    function search(name) {
        if (visited.has(name)) return null;
        visited.add(name);
        const typeNode = mergedTypes.get(name);
        if (!typeNode) return null;
        for (const f of typeNode.fields) {
            if (f.fieldName === fieldName) return f.typeName;
        }
        for (const parent of (typeNode.parents || [])) {
            const result = search(parent);
            if (result !== null) return result;
        }
        return null;
    }
    return search(typeName);
}

function isObjectTypedField(field, typeName, mergedTypes, kindNames) {
    if (field.value.kind !== "StringLiteral") return false;
    const fieldType = resolveFieldType(typeName, field.fieldName, mergedTypes);
    return fieldType !== null && !PRIMITIVE_TYPES.has(fieldType) && !kindNames.has(fieldType);
}

function objectRef(objectName) {
    return /^[A-Za-z_][A-Za-z0-9_]*$/.test(objectName)
        ? objectName
        : `lamplighter.getObject(${JSON.stringify(objectName)})`;
}

function emitGlobalDecl(node, kindNames = new Set()) {
    let valueExpr;
    if (node.value.kind === "NoneLiteral") {
        valueExpr = "null";
    } else if (
        node.value.kind === "StringLiteral"
        && !PRIMITIVE_TYPES.has(node.typeName)
        && !kindNames.has(node.typeName)
    ) {
        // Bare identifier value for an object-typed global — treat as object name reference
        valueExpr = `lamplighter.getObject(${JSON.stringify(node.value.value)})`;
    } else {
        valueExpr = emitValue(node.value);
    }
    return `lamplighter.defineGlobal(${JSON.stringify(node.name)}, ${valueExpr});`;
}

function emitGlobalAssign(node) {
    return `lamplighter.setGlobal(${JSON.stringify(node.name)}, ${emitValue(node.value)});`;
}

function emitKindDecl(node) {
    return `lamplighter.defineKind(${JSON.stringify(node.name)}, ${emitKindExpr(node.kindExpr)});`;
}

function emitKindExpr(expr) {
    if (expr.kind === "EnumExpr") {
        const labelArgs = expr.labels.map((l) => JSON.stringify(l)).join(", ");
        return `lamplighter.enum(${labelArgs})`;
    }
    throw new Error(`Unsupported kind expression kind: ${expr.kind}`);
}

function emitTypeDecl(node) {
    const fields = {};
    for (const field of node.fields) {
        fields[field.fieldName] = field.typeName;
    }

    return `lamplighter.defineType(${JSON.stringify(node.name)}, ${JSON.stringify(node.parents || [])}, ${JSON.stringify(fields)});`;
}

function emitRelationDecl(node) {
    const fields = {};
    for (const field of node.fields) {
        fields[field.fieldName] = field.typeName;
    }
    const syntaxArg = node.syntax === null ? "null" : JSON.stringify(node.syntax);
    return `lamplighter.defineRelation(${JSON.stringify(node.name)}, ${JSON.stringify(fields)}, ${syntaxArg}, ${JSON.stringify(node.invertedFields || [])});`;
}

function emitRelationAssert(node) {
    const schema = relationFieldSchemas.get(node.relationName) || {};
    const pairs = node.fields.map((field) => {
        const fieldType = schema[field.fieldName];
        const isObjectTyped = field.value.kind === "StringLiteral"
            && fieldType !== undefined
            && !PRIMITIVE_TYPES.has(fieldType)
            && !emitKindNames.has(fieldType);
        const valueExpr = isObjectTyped
            ? `lamplighter.getObject(${JSON.stringify(field.value.value)})`
            : emitValue(field.value);
        return `${JSON.stringify(field.fieldName)}: ${valueExpr}`;
    });
    const opts = [];
    if (node.instanceName) opts.push(`name: ${JSON.stringify(node.instanceName)}`);
    if (node.bidi) opts.push("bidi: true");
    const optionsArg = opts.length > 0 ? `, { ${opts.join(", ")} }` : "";
    return `lamplighter.addRelation(${JSON.stringify(node.relationName)}, { ${pairs.join(", ")} }${optionsArg});`;
}

function emitRelationRemove(node, globalNames = new Set()) {
    const schema = relationFieldSchemas.get(node.relationName) || {};
    const specifiedFields = new Map(node.fields.map((f) => [f.fieldName, f.value]));
    const pairs = Object.keys(schema).map((fieldName) => {
        const value = specifiedFields.get(fieldName);
        let valueExpr;
        if (!value || value.kind === "WildcardExpr") {
            valueExpr = "lamplighter.ANY";
        } else if (
            value.kind === "StringLiteral"
            && !PRIMITIVE_TYPES.has(schema[fieldName])
            && !emitKindNames.has(schema[fieldName])
        ) {
            valueExpr = `lamplighter.getObject(${JSON.stringify(value.value)})`;
        } else {
            valueExpr = emitExpression(value, globalNames);
        }
        return `${JSON.stringify(fieldName)}: ${valueExpr}`;
    });
    return `lamplighter.removeRelation(${JSON.stringify(node.relationName)}, { ${pairs.join(", ")} });`;
}

function emitDisconnect(node) {
    return `lamplighter.removeRelationByName(${JSON.stringify(node.instanceName)});`;
}

// Emits a call's argument list. A bare object name parses to a StringLiteral
// (indistinguishable from a quoted string in the AST), so — as with object field
// values — when the parameter is object-typed it is resolved via getObject.
function emitCallArgs(functionName, args, globalNames) {
    const paramTypes = functionParamTypes.get(functionName) || [];
    return args
        .map((arg, i) => {
            const paramType = paramTypes[i];
            if (
                arg.kind === "StringLiteral"
                && paramType !== undefined
                && paramType !== "function"
                && !PRIMITIVE_TYPES.has(paramType)
                && !emitKindNames.has(paramType)
                && !paramType.startsWith("list<")
            ) {
                return `lamplighter.getObject(${JSON.stringify(arg.value)})`;
            }
            return emitExpression(arg, globalNames);
        })
        .join(", ");
}

function emitRelationQuery(node, globalNames) {
    const schema = relationFieldSchemas.get(node.relationName) || {};
    const pairs = node.fields.map((field) => {
        const fieldType = schema[field.fieldName];
        let valueExpr;
        if (field.value.kind === "WildcardExpr") {
            valueExpr = "lamplighter.ANY";
        } else if (
            field.value.kind === "StringLiteral"
            && fieldType !== undefined
            && !PRIMITIVE_TYPES.has(fieldType)
            && !emitKindNames.has(fieldType)
        ) {
            valueExpr = `lamplighter.getObject(${JSON.stringify(field.value.value)})`;
        } else {
            valueExpr = emitExpression(field.value, globalNames);
        }
        return `${JSON.stringify(field.fieldName)}: ${valueExpr}`;
    });
    const mapping = `{ ${pairs.join(", ")} }`;
    if (!node.outputField) {
        return `(lamplighter.queryRelation(${JSON.stringify(node.relationName)}, ${mapping}).length > 0)`;
    }
    return `lamplighter.queryRelationValue(${JSON.stringify(node.relationName)}, ${mapping}, ${JSON.stringify(node.outputField)}, ${JSON.stringify(node.outputMode)})`;
}

function emitObjectDecl(node, mergedTypes = new Map(), kindNames = new Set()) {
    const fields = {};
    for (const field of node.fields) {
        if (!isObjectTypedField(field, node.typeName, mergedTypes, kindNames)) {
            fields[field.fieldName] = emitValue(field.value);
        }
    }

    const pairs = Object.entries(fields).map(([key, value]) => `${JSON.stringify(key)}: ${value}`);
    const call = `lamplighter.createObject(${JSON.stringify(node.typeName)}, ${JSON.stringify(node.objectName)}, { ${pairs.join(", ")} })`;

    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(node.objectName)) {
        return `const ${node.objectName} = ${call};`;
    }
    return `${call};`;
}

function emitObjectFieldInits(node, mergedTypes, kindNames) {
    return node.fields
        .filter((field) => isObjectTypedField(field, node.typeName, mergedTypes, kindNames))
        .map((field) => `${objectRef(node.objectName)}.${field.fieldName} = lamplighter.getObject(${JSON.stringify(field.value.value)});`);
}

function emitValue(valueNode) {
    if (valueNode.kind === "StringLiteral") {
        return JSON.stringify(valueNode.value);
    }
    if (valueNode.kind === "BooleanLiteral") {
        return valueNode.value ? "true" : "false";
    }
    if (valueNode.kind === "NumberLiteral") {
        return String(valueNode.value);
    }
    if (valueNode.kind === "NoneLiteral") {
        return "null";
    }
    throw new Error(`Unsupported value kind: ${valueNode.kind}`);
}

function emitFunctionDecl(node, globalNames = new Set()) {
    const paramList = node.params.map((p) => p.name).join(", ");
    const bodyLines = emitStatementList(node.body, 1, globalNames);
    return [
        `function ${node.name}(${paramList}) {`,
        ...bodyLines,
        "}",
    ].join("\n");
}

function computeSpecificity(expr) {
    if (expr.kind === "AndExpr") return computeSpecificity(expr.left) + computeSpecificity(expr.right);
    if (expr.kind === "OrExpr") return Math.max(computeSpecificity(expr.left), computeSpecificity(expr.right));
    if (expr.kind === "NotExpr") return computeSpecificity(expr.expr);
    if (expr.kind === "RelationQuery") return expr.fields.filter((f) => f.value.kind !== "WildcardExpr").length;
    return 1;
}

function emitFunctionGroup(name, overloads, globalNames) {
    const unconditional = overloads.find((o) => o.node.whenExpr === null);
    const conditionals = overloads
        .filter((o) => o.node.whenExpr !== null)
        .map((o) => ({ node: o.node, index: o.definitionIndex, specificity: computeSpecificity(o.node.whenExpr) }))
        .sort((a, b) => b.specificity !== a.specificity ? b.specificity - a.specificity : b.index - a.index);

    const referenceNode = (unconditional || conditionals[0]).node;
    const paramList = referenceNode.params.map((p) => p.name).join(", ");

    const lines = [];
    lines.push(`function ${name}(${paramList}) {`);

    if (conditionals.length === 0) {
        lines.push(...emitStatementList(referenceNode.body, 1, globalNames));
    } else {
        const [first, ...rest] = conditionals;
        lines.push(`    if (${emitExpression(first.node.whenExpr, globalNames)}) {`);
        lines.push(...emitStatementList(first.node.body, 2, globalNames));
        for (const cond of rest) {
            lines.push(`    } else if (${emitExpression(cond.node.whenExpr, globalNames)}) {`);
            lines.push(...emitStatementList(cond.node.body, 2, globalNames));
        }
        lines.push(`    } else {`);
        if (unconditional) {
            lines.push(...emitStatementList(unconditional.node.body, 2, globalNames));
        } else {
            lines.push(`        throw new Error(\`no matching version of ${name} for current game state\`);`);
        }
        lines.push(`    }`);
    }

    lines.push("}");
    return lines.join("\n");
}

// A rulebook compiles to a plain (hoisted) JS function: each rule is an
// `if (guard) { ...body... }` whose `stop EXPR` emits a `return EXPR`. A body
// that does not stop falls through to the next rule; once all rules are
// exhausted the default value is returned. `follow NAME(args)` is emitted as an
// ordinary call, so no runtime support is required.
function emitRulebookDecl(node, globalNames = new Set()) {
    const paramList = node.params.map((p) => p.name).join(", ");
    const lines = [`function ${node.name}(${paramList}) {`];
    for (const rule of node.rules) {
        lines.push(`    if (${emitExpression(rule.whenExpr, globalNames)}) {`);
        lines.push(...emitStatementList(rule.body, 2, globalNames));
        lines.push(`    }`);
    }
    lines.push(`    return ${emitExpression(node.defaultExpr, globalNames)};`);
    lines.push("}");
    return lines.join("\n");
}

function emitEventHandler(node, globalNames = new Set()) {
    const bodyLines = emitStatementList(node.body, 1, globalNames);
    return [
        `lamplighter.onEvent(${JSON.stringify(node.eventName)}, () => {`,
        ...bodyLines,
        "});",
    ].join("\n");
}

// A phase rule registers a function into the action's rulebook band. The
// function receives the action instance as `self`; a `stop EXPR` emits as
// `return EXPR`, and the driver treats any returned value as a stop-with-outcome
// while a fall-through (undefined) continues to the next rule.
function emitPhaseRule(node, globalNames = new Set()) {
    const lines = [
        `lamplighter.registerActionRule(${JSON.stringify(node.actionName)}, ${JSON.stringify(node.band)}, (self) => {`,
    ];
    if (node.whenExpr) {
        lines.push(`    if (!(${emitExpression(node.whenExpr, globalNames)})) return;`);
    }
    lines.push(...emitStatementList(node.body, 1, globalNames));
    lines.push("});");
    return lines.join("\n");
}

function emitChangeHandler(node, globalNames = new Set()) {
    const bodyLines = emitStatementList(node.body, 1, globalNames);
    return [
        `lamplighter.registerChangeHandler(${JSON.stringify(node.typeName)}, ${JSON.stringify(node.fieldName)}, (self) => {`,
        ...bodyLines,
        "});",
    ].join("\n");
}

function emitRelationAddHandler(node, globalNames = new Set()) {
    const bodyLines = emitStatementList(node.body, 1, globalNames);
    return [
        `lamplighter.registerRelationAddHandler(${JSON.stringify(node.relationName)}, (self) => {`,
        ...bodyLines,
        "});",
    ].join("\n");
}

function emitRelationRemoveHandler(node, globalNames = new Set()) {
    const bodyLines = emitStatementList(node.body, 1, globalNames);
    return [
        `lamplighter.registerRelationRemoveHandler(${JSON.stringify(node.relationName)}, (self) => {`,
        ...bodyLines,
        "});",
    ].join("\n");
}

function emitStatementList(statements, indentLevel, globalNames = new Set()) {
    return statements.flatMap((statement) => emitStatementLines(statement, indentLevel, globalNames));
}

function emitStatementLines(statement, indentLevel, globalNames = new Set()) {
    const indent = "    ".repeat(indentLevel);

    if (statement.kind === "LetStatement") {
        return [`${indent}let ${statement.name} = ${emitExpression(statement.expr, globalNames)};`];
    }
    if (statement.kind === "PrintStatement") {
        return [`${indent}lamplighter.print(${emitExpression(statement.expr, globalNames)});`];
    }
    if (statement.kind === "AssignStatement") {
        const [head, ...tail] = statement.targetChain;
        const valueExpr = emitExpression(statement.expr, globalNames);
        if (tail.length === 0 && globalNames.has(head)) {
            return [`${indent}lamplighter.setGlobal(${JSON.stringify(head)}, ${valueExpr});`];
        }
        const headExpr = globalNames.has(head) ? `lamplighter.getGlobal(${JSON.stringify(head)})` : head;
        if (tail.length === 0) {
            return [`${indent}${head} = ${valueExpr};`];
        }
        const objExpr = tail.length === 1 ? headExpr : `${headExpr}.${tail.slice(0, -1).join(".")}`;
        const fieldName = tail[tail.length - 1];
        return [`${indent}lamplighter.setField(${objExpr}, ${JSON.stringify(fieldName)}, ${valueExpr});`];
    }
    if (statement.kind === "ErrorStatement") {
        return [`${indent}lamplighter.error(${emitExpression(statement.expr, globalNames)});`];
    }
    if (statement.kind === "DispatchStatement") {
        return [`${indent}lamplighter.dispatch(${JSON.stringify(statement.eventName)});`];
    }
    if (statement.kind === "IfStatement") {
        const lines = [`${indent}if (${emitExpression(statement.condition, globalNames)}) {`];
        lines.push(...emitStatementList(statement.thenBody, indentLevel + 1, globalNames));
        lines.push(`${indent}}`);

        if (statement.elseBody) {
            lines[lines.length - 1] = `${indent}} else {`;
            lines.push(...emitStatementList(statement.elseBody, indentLevel + 1, globalNames));
            lines.push(`${indent}}`);
        }

        return lines;
    }
    if (statement.kind === "BreakStatement") {
        return [`${indent}break;`];
    }
    if (statement.kind === "ForStatement") {
        const start = emitExpression(statement.start, globalNames);
        const finish = emitExpression(statement.finish, globalNames);
        const step = emitExpression(statement.step, globalNames);
        const v = statement.varName;
        const lines = [`${indent}for (let ${v} = ${start}; ${v} <= ${finish}; ${v} += ${step}) {`];
        lines.push(...emitStatementList(statement.body, indentLevel + 1, globalNames));
        lines.push(`${indent}}`);
        return lines;
    }
    if (statement.kind === "ForEachStatement") {
        const listExpr = emitExpression(statement.listExpr, globalNames);
        const v = statement.varName;
        const lines = [`${indent}for (const ${v} of lamplighter.listItems(${listExpr})) {`];
        lines.push(...emitStatementList(statement.body, indentLevel + 1, globalNames));
        lines.push(`${indent}}`);
        return lines;
    }
    if (statement.kind === "WhileStatement") {
        const lines = [`${indent}while (${emitExpression(statement.condition, globalNames)}) {`];
        lines.push(...emitStatementList(statement.body, indentLevel + 1, globalNames));
        lines.push(`${indent}}`);
        return lines;
    }
    if (statement.kind === "RelationAssert") {
        return [`${indent}${emitRelationAssert(statement)}`];
    }
    if (statement.kind === "RelationRemove") {
        return [`${indent}${emitRelationRemove(statement, globalNames)}`];
    }
    if (statement.kind === "DisconnectStatement") {
        return [`${indent}${emitDisconnect(statement)}`];
    }
    if (statement.kind === "CallStatement") {
        const argExprs = emitCallArgs(statement.name, statement.args, globalNames);
        return [`${indent}${statement.name}(${argExprs});`];
    }
    if (statement.kind === "ReturnStatement") {
        if (statement.expr === null) return [`${indent}return;`];
        return [`${indent}return ${emitExpression(statement.expr, globalNames)};`];
    }
    if (statement.kind === "StopStatement") {
        if (statement.expr === null) return [`${indent}return;`];
        if (statement.reason) {
            return [
                `${indent}self.reason = ${emitExpression(statement.reason, globalNames)};`,
                `${indent}return ${emitExpression(statement.expr, globalNames)};`,
            ];
        }
        return [`${indent}return ${emitExpression(statement.expr, globalNames)};`];
    }
    if (statement.kind === "FollowStatement") {
        const argExprs = emitCallArgs(statement.name, statement.args, globalNames);
        return [`${indent}${statement.name}(${argExprs});`];
    }
    if (statement.kind === "TryStatement") {
        const slotTypes = actionSlotTypes.get(statement.actionName) || new Map();
        const pairs = statement.fields.map((field) => {
            const slotType = slotTypes.get(field.fieldName);
            const isObject = field.value.kind === "StringLiteral"
                && slotType !== undefined
                && !PRIMITIVE_TYPES.has(slotType)
                && !emitKindNames.has(slotType);
            const valueExpr = isObject
                ? `lamplighter.getObject(${JSON.stringify(field.value.value)})`
                : emitValue(field.value);
            return `${JSON.stringify(field.fieldName)}: ${valueExpr}`;
        });
        const instance = `{ "type": ${JSON.stringify(statement.actionName)}${pairs.length ? ", " + pairs.join(", ") : ""} }`;
        return [`${indent}lamplighter.runAction(${JSON.stringify(statement.actionName)}, ${instance});`];
    }
    throw new Error(`Unsupported statement kind: ${statement.kind}`);
}

function emitExpression(expr, globalNames = new Set()) {
    if (expr.kind === "StringLiteral") {
        return JSON.stringify(expr.value);
    }
    if (expr.kind === "VariableExpr") {
        return expr.name;
    }
    if (expr.kind === "BooleanLiteral") {
        return expr.value ? "true" : "false";
    }
    if (expr.kind === "NumberLiteral") {
        return String(expr.value);
    }
    if (expr.kind === "IndexExpr") {
        return `${emitExpression(expr.target, globalNames)}.items[${emitExpression(expr.index, globalNames)}]`;
    }
    if (expr.kind === "PropertyAccess") {
        const [head, ...tail] = expr.chain;
        const headExpr = globalNames.has(head) ? `lamplighter.getGlobal(${JSON.stringify(head)})` : head;
        return tail.length === 0 ? headExpr : `${headExpr}.${tail.join(".")}`;
    }
    if (expr.kind === "Concat") {
        return `lamplighter.concat(${emitExpression(expr.left, globalNames)}, ${emitExpression(expr.right, globalNames)})`;
    }
    if (expr.kind === "EqualsExpr") {
        return `${emitExpression(expr.left, globalNames)} === ${emitExpression(expr.right, globalNames)}`;
    }
    if (expr.kind === "LessThanExpr") {
        return `${emitExpression(expr.left, globalNames)} < ${emitExpression(expr.right, globalNames)}`;
    }
    if (expr.kind === "LessOrEqualExpr") {
        return `${emitExpression(expr.left, globalNames)} <= ${emitExpression(expr.right, globalNames)}`;
    }
    if (expr.kind === "MultiplyExpr") {
        return `${wrapIfNeeded(expr.left, 14, globalNames)} * ${wrapIfNeeded(expr.right, 14, globalNames, { rightOperand: true })}`;
    }
    if (expr.kind === "NegateExpr") {
        return `-(${emitExpression(expr.expr, globalNames)})`;
    }
    if (expr.kind === "SubtractExpr") {
        return `${wrapIfNeeded(expr.left, 13, globalNames)} - ${wrapIfNeeded(expr.right, 13, globalNames, { rightOperand: true })}`;
    }
    if (expr.kind === "DivideExpr") {
        return `lamplighter.divide(${emitExpression(expr.left, globalNames)}, ${emitExpression(expr.right, globalNames)})`;
    }
    if (expr.kind === "PowerExpr") {
        return `${wrapIfNeeded(expr.left, 15, globalNames, { leftOfPower: true })} ** ${wrapIfNeeded(expr.right, 15, globalNames)}`;
    }
    if (expr.kind === "NoneLiteral") {
        return "null";
    }
    if (expr.kind === "GlobalExpr") {
        return `lamplighter.getGlobal(${JSON.stringify(expr.name)})`;
    }
    if (expr.kind === "ParenNameExpr") {
        const base = `lamplighter.getObject(${JSON.stringify(expr.objectName)})`;
        return expr.fieldChain.length === 0 ? base : `${base}.${expr.fieldChain.join(".")}`;
    }
    if (expr.kind === "CallExpr") {
        return `${expr.name}(${emitCallArgs(expr.name, expr.args, globalNames)})`;
    }
    if (expr.kind === "FunctionRefExpr") {
        return expr.name;
    }
    if (expr.kind === "FollowExpr") {
        return `${expr.name}(${emitCallArgs(expr.name, expr.args, globalNames)})`;
    }
    if (expr.kind === "AndExpr") {
        return `(${emitExpression(expr.left, globalNames)} && ${emitExpression(expr.right, globalNames)})`;
    }
    if (expr.kind === "OrExpr") {
        return `(${emitExpression(expr.left, globalNames)} || ${emitExpression(expr.right, globalNames)})`;
    }
    if (expr.kind === "NotExpr") {
        return `!(${emitExpression(expr.expr, globalNames)})`;
    }
    if (expr.kind === "RelationQuery") {
        return emitRelationQuery(expr, globalNames);
    }
    throw new Error(`Unsupported expression kind: ${expr.kind}`);
}

module.exports = {
    emitProgram,
};
