function emitProgram(programAst, options = {}) {
    const runtimeRequirePath = options.runtimeRequirePath || "../lamplighter";
    const globalDeclNodes = programAst.nodes.filter((node) => node.kind === "GlobalDecl");
    const globalAssignNodes = programAst.nodes.filter((node) => node.kind === "GlobalAssign");
    const kindNodes = programAst.nodes.filter((node) => node.kind === "KindDecl");
    const typeNodes = programAst.nodes.filter((node) => node.kind === "TypeDecl");
    const objectNodes = programAst.nodes.filter((node) => node.kind === "ObjectDecl");
    const eventNodes = programAst.nodes.filter((node) => node.kind === "EventHandler");

    const lines = [];
    lines.push("#!/usr/bin/env node");
    lines.push("/* Generated by Lantern */");
    lines.push(`const lamplighter = require(${JSON.stringify(runtimeRequirePath)});`);
    lines.push("lamplighter.bootstrapBuiltins();");
    lines.push("");

    for (const globalDeclNode of globalDeclNodes) {
        lines.push(emitGlobalDecl(globalDeclNode));
    }

    if (globalDeclNodes.length > 0) {
        lines.push("");
    }

    for (const globalAssignNode of globalAssignNodes) {
        lines.push(emitGlobalAssign(globalAssignNode));
    }

    if (globalAssignNodes.length > 0) {
        lines.push("");
    }

    for (const kindNode of kindNodes) {
        lines.push(emitKindDecl(kindNode));
    }

    if (kindNodes.length > 0) {
        lines.push("");
    }

    for (const kindNode of kindNodes) {
        lines.push(`const ${kindNode.name} = lamplighter.kind(${JSON.stringify(kindNode.name)});`);
    }

    if (kindNodes.length > 0) {
        lines.push("");
    }

    for (const typeNode of typeNodes) {
        lines.push(emitTypeDecl(typeNode));
    }

    if (typeNodes.length > 0) {
        lines.push("");
    }

    for (const typeNode of typeNodes) {
        lines.push(`const ${typeNode.name} = lamplighter.type(${JSON.stringify(typeNode.name)});`);
    }

    if (typeNodes.length > 0) {
        lines.push("");
    }

    for (const objectNode of objectNodes) {
        lines.push(emitObjectDecl(objectNode));
    }

    if (objectNodes.length > 0) {
        lines.push("");
    }

    for (const eventNode of eventNodes) {
        lines.push(emitEventHandler(eventNode));
    }

    lines.push("");
    lines.push("lamplighter.run();");
    lines.push("");

    return `${lines.join("\n")}`;
}

function emitGlobalDecl(node) {
    return `lamplighter.defineGlobal(${JSON.stringify(node.name)}, ${emitValue(node.value)});`;
}

function emitGlobalAssign(node) {
    return `lamplighter.setGlobal(${JSON.stringify(node.name)}, ${emitValue(node.value)});`;
}

function emitKindDecl(node) {
    return `lamplighter.defineKind(${JSON.stringify(node.name)}, ${emitKindExpr(node.kindExpr)});`;
}

function emitKindExpr(expr) {
    if (expr.kind === "EnumExpr") {
        const labelArgs = expr.labels.map((l) => JSON.stringify(l)).join(", ");
        return `lamplighter.enum(${labelArgs})`;
    }
    throw new Error(`Unsupported kind expression kind: ${expr.kind}`);
}

function emitTypeDecl(node) {
    const fields = {};
    for (const field of node.fields) {
        fields[field.fieldName] = field.typeName;
    }

    return `lamplighter.defineType(${JSON.stringify(node.name)}, ${JSON.stringify(node.parents || [])}, ${JSON.stringify(fields)});`;
}

function emitObjectDecl(node) {
    const fields = {};
    for (const field of node.fields) {
        fields[field.fieldName] = emitValue(field.value);
    }

    const pairs = Object.entries(fields).map(([key, value]) => `${JSON.stringify(key)}: ${value}`);
    const call = `lamplighter.createObject(${JSON.stringify(node.typeName)}, ${JSON.stringify(node.objectName)}, { ${pairs.join(", ")} })`;

    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(node.objectName)) {
        return `const ${node.objectName} = ${call};`;
    }
    return `${call};`;
}

function emitValue(valueNode) {
    if (valueNode.kind === "StringLiteral") {
        return JSON.stringify(valueNode.value);
    }
    if (valueNode.kind === "BooleanLiteral") {
        return valueNode.value ? "true" : "false";
    }
    if (valueNode.kind === "NumberLiteral") {
        return String(valueNode.value);
    }
    throw new Error(`Unsupported value kind: ${valueNode.kind}`);
}

function emitEventHandler(node) {
    const bodyLines = emitStatementList(node.body, 1);
    return [
        `lamplighter.onEvent(${JSON.stringify(node.eventName)}, () => {`,
        ...bodyLines,
        "});",
    ].join("\n");
}

function emitStatementList(statements, indentLevel) {
    return statements.flatMap((statement) => emitStatementLines(statement, indentLevel));
}

function emitStatementLines(statement, indentLevel) {
    const indent = "    ".repeat(indentLevel);

    if (statement.kind === "LetStatement") {
        return [`${indent}let ${statement.name} = ${emitExpression(statement.expr)};`];
    }
    if (statement.kind === "PrintStatement") {
        return [`${indent}lamplighter.print(${emitExpression(statement.expr)});`];
    }
    if (statement.kind === "AssignStatement") {
        return [`${indent}${statement.targetChain.join(".")} = ${emitExpression(statement.expr)};`];
    }
    if (statement.kind === "ErrorStatement") {
        return [`${indent}lamplighter.error(${emitExpression(statement.expr)});`];
    }
    if (statement.kind === "IfStatement") {
        const lines = [`${indent}if (${emitExpression(statement.condition)}) {`];
        lines.push(...emitStatementList(statement.thenBody, indentLevel + 1));
        lines.push(`${indent}}`);

        if (statement.elseBody) {
            lines[lines.length - 1] = `${indent}} else {`;
            lines.push(...emitStatementList(statement.elseBody, indentLevel + 1));
            lines.push(`${indent}}`);
        }

        return lines;
    }
    throw new Error(`Unsupported statement kind: ${statement.kind}`);
}

function emitExpression(expr) {
    if (expr.kind === "StringLiteral") {
        return JSON.stringify(expr.value);
    }
    if (expr.kind === "VariableExpr") {
        return expr.name;
    }
    if (expr.kind === "BooleanLiteral") {
        return expr.value ? "true" : "false";
    }
    if (expr.kind === "NumberLiteral") {
        return String(expr.value);
    }
    if (expr.kind === "PropertyAccess") {
        return expr.chain.join(".");
    }
    if (expr.kind === "Concat") {
        return `${emitExpression(expr.left)} + ${emitExpression(expr.right)}`;
    }
    if (expr.kind === "EqualsExpr") {
        return `${emitExpression(expr.left)} === ${emitExpression(expr.right)}`;
    }
    if (expr.kind === "MultiplyExpr") {
        return `${emitExpression(expr.left)} * ${emitExpression(expr.right)}`;
    }
    if (expr.kind === "GlobalExpr") {
        return `lamplighter.getGlobal(${JSON.stringify(expr.name)})`;
    }
    if (expr.kind === "ParenNameExpr") {
        const base = `lamplighter.getObject(${JSON.stringify(expr.objectName)})`;
        return expr.fieldChain.length === 0 ? base : `${base}.${expr.fieldChain.join(".")}`;
    }
    throw new Error(`Unsupported expression kind: ${expr.kind}`);
}

module.exports = {
    emitProgram,
};
